version: '3'

services:

  api:
    build: ./src
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    command: bash -c "flask run --host 0.0.0.0"
    restart: always