version: '3'

services:

  api:
    build: ./src
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    command: bash -c "flask run --host 0.0.0.0"
    restart: always
    depends_on:
      - db
  
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    restart: always